### ISSUE TITLE
Error when Claiming tokens via Gnosis App

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1041]
Steps to reproduce:
1. Follow the instructions here to use Gnosis Safe App 
https://www.notion.so/primedao/WIP-Gnosis-Safe-App-Instructions-2ef58ab2d719472185055430ff6de227#0760d7ee415d408da9fb38adddf7547c
2. Connect your wallet: 0xE834627cDE2dC8F55Fe4a26741D3e91527A8a498
3. Go to here: https://prime-deals-dapp-git-feat-988-gnosis-safe-curvelabs.vercel.app/deal/87YemHJ6ToocxzcPLQqkpi
4. Go to claim and claim tokens

Result: 
Console log throws:
Failed to load resource: the server responded with a status of 404 (Not Found)
safe-client.gnosis.io/v1/chains/4/transactions/0x40597Caffbc904396DCAFD23786A0e1626E6975c/propose:1          Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
instrument.ts:129 Code 816: Error saving transaction to history (1337: {"nonFieldErrors":["Tx with nonce=32 for safe=0x40597Caffbc904396DCAFD23786A0e1626E6975c already executed in tx-hash=0x4177386802c4912ac40def8e3e45fa3d1a613570f58a4aba4ff3baeb4fd41787"]})

**Comment by hiaux0** [comment]
Worked in latest tests
