### ISSUE TITLE
Display treasury addresses in the deal dashboard

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1044]
Current:
We do not display Treasury address in our UI

Expected:
To be able to see the treasury address for a DAO under Primary/Partner DAO funds.
Title should be "Treasury".
And the UI implementation of Treasury should be similar to how we display "Proposal Lead" and it's address.

![2022-05-28 14.50.46.jpg](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/eab10c9e-3bf5-4fe3-8665-f2b0d50198d4)

**Comment by blink-km** [comment]
#1065
