### ISSUE TITLE
Deal status changes after reloading the deal dashboard

### ISSUE THREAD

**Issue by giladt** [PrimeDAO/prime-deals-dapp#1102]
Steps to reproduce:
1. Navigate to the all-deals page
2. Choose 'Partnered Deals' -> 'Swap TX Hash Test'
3. The vote section shows 'Deal Status' -> `Completed`

<img src="https://images.zenhubusercontent.com/60c89178ac3fd01fa6c9ba4a/f692dd91-6eea-4cca-a1da-63c64c5249cf" width="300">

4. Refresh the page (using the refresh button in the browser) or navigate [here](https://prime-deals-dapp-git-refac-deals-au2-staging-curvelabs.vercel.app/deal/gk875LTy76x8JUTkMuVPJg)
5. The vote section shows now 'Deal Status' -> 'Claiming'

<img src="https://images.zenhubusercontent.com/60c89178ac3fd01fa6c9ba4a/36512337-046a-4914-8022-8e9cdce66462" width="300">

Expected:
Deal Status should only show 'Completed' for this deal.

**Comment by hiaux0** [comment]
fixed by PR #1178
