### ISSUE TITLE
Investigate: Change router package to `@aurelia/router-lite`

### ISSUE THREAD

**Issue by hiaux0** [PrimeDAO/prime-deals-dapp#1107]
Challenges
- no docs for router-lite
- will need api changes from `@aurelia/router`

**Comment by IonelLupu** [comment]
tried router-list but got errors like:
![image](https://user-images.githubusercontent.com/4083652/185169884-9642d880-52ba-4ad9-b3c8-7284b63a96bd.png)
or 
![image](https://user-images.githubusercontent.com/4083652/185170048-3a5a5838-86cb-4929-a992-8da879b4e7f5.png)


And lack of docs.

Also, the kolektivo team isn't using it
