### ISSUE TITLE
Deal Dashboard should automatically update correctly after token swap is executed

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1110]
I have executed token swap and the deal dashboard was not automatically updated. However after refreshing the page, everything has correctly updated!
Here: https://prime-deals-dapp-git-refac-deals-au2-staging-curvelabs.vercel.app/deal/nacEB2ZAA7ioD9KUyWjsfX

Currently:
1. Token status field is not displaying correct information
![Deal-dashboard-Prime-Deals (11)](https://user-images.githubusercontent.com/24368665/177161560-e3c88051-8f49-4ef7-8e07-bbd0c09c5ed0.png)

2. Vote section is outdated
![Deal-dashboard-Prime-Deals (10)](https://user-images.githubusercontent.com/24368665/177161572-2fe76b51-944b-4851-af4c-63d5b4665c34.png)

**Comment by hiaux0** [comment]
Closing, because each task is tracked by 
1. #1161
2. #1160
