### ISSUE TITLE
Refreshing the page should not disconnect wallet

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1157]
1.Navigate here: https://prime-deals-dapp-jhff2ozmg-curvelabs.vercel.app/
2.Connect wallet
3.Refresh page

Result:
Wallet will be disconnected

Expected:
Wallet to stay connected

**Comment by IonelLupu** [comment]
Cannot replicate. @BartuCulha can you replicate right now?

**Comment by IonelLupu** [comment]
kind reminder @BartuCulha

**Comment by BartuCulha** [comment]
no i cant, closing this ticket!
