### ISSUE TITLE
Dashboard: Begin a discussion button inside a clause is misplaced

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#1204]
Navigate here: https://prime-deals-au2-staging.vercel.app/deal/aQ8K7MJcJMe5fuaTqCEM7m
Connect wallet (0xE834627cDE2dC8F55Fe4a26741D3e91527A8a498)
Hover over a clause to begin a discussion

Result:
Begin a discussion is misplaced
![Deal-dashboard-Prime-Deals (7).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/15388608-6523-464d-b4a5-8422b85eb115)

Expected:
![DEAL-Dashboard-Prime-Deals (6).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/5258957a-964b-49a3-8a35-bb5801c48082)

**Comment by hiaux0** [comment]
@BartuCulha fyi, expected change in the feature

https://www.figma.com/file/hTLvqCEzki3WoG5uJbtynw/Prime-Deals?node-id=11857%3A170176

![image.png](https://images.zenhubusercontent.com/61d459cd2e1f45dd77990d23/be501e11-fb68-41ab-9529-dc930e179ab7)

**Comment by BartuCulha** [comment]
Thank youu
