### ISSUE TITLE
Footer Items and Order

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#231]
![Home _ Prime Deals (1)](https://user-images.githubusercontent.com/24368665/155766047-78d32b7e-a2e8-4c60-9f23-45585bec3c80.png)

Items and order should be like above:
Docs,  Support, Privacy,  Terms 

Documentation goes to .../documentation
Support goes to: https://form.typeform.com/to/SUCTM812
Privacy - privacy acknowledgment document (To be added)
Terms - Legal disclaimer document(To be added)

**Comment by dkent600** [comment]
Dup of https://github.com/PrimeDAO/prime-deals-dapp/issues/228
