### ISSUE TITLE
Open Proposals cannot be private

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#301]
Navigate here:
https://prime-deals-staging.vercel.app/deal/open_deals_stream_hash_1

I'm seeing this text under the title:
"* Active, Recently updated (Private)"

Expected:
Open proposals cannot be private they are public only.

**Comment by giladt** [comment]
@BartuCulha Deal Dashboard is currently only a mock and should not be tested. The only thing to test is the Clauses section and the Discussion section. I believe this issue can be closed.

cc: @dkent600
