### ISSUE TITLE
FormattedNumber's tooltip should also use "," for long numbers

### ISSUE THREAD

**Issue by hiaux0** [PrimeDAO/prime-deals-dapp#357]
Relates to #344
in Token Details and Submit stage for the token information card.

Idea: Any long number should handle this by default (in `<formatted-number>`)

![image](https://user-images.githubusercontent.com/30693990/158166603-2359914b-38b7-4269-9036-43e4ccfb6111.png)

**Comment by curvelabs-dev** [comment]
I would prefer to not refactor code to make it be the default.  You can supply `| withCommas`.

**Comment by hiaux0** [comment]
`Optional` label reason

Show the "raw" number for user to copy paste

**Comment by curvelabs-dev** [comment]
I don't support making this be the default.  Should probably close this ticket.
