### ISSUE TITLE
"Connect to show your deals" should show correct gradient during hover

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#466]
Please change the color of "Connect to show your deals" during hover. It should have the same collor as connect your wallet button on the navbar

Expected:
![Deals-Prime-Deals (2).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/6b0a6f45-7411-410c-8559-0feb4874e3af)

Result:
![Deals-Prime-Deals (3).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/5d06132c-7501-48da-b28e-3491ab9487d8)

**Comment by curvelabs-dev** [comment]
@BartuCulha Chad and I don't agree with you on this.  It is not usual UX to have two "primary" buttons.  Thus we have provided one primary and one secondary.  It also gives some nice variety to the presentation, IMHO, ie, looks good.  Of course this is debatable, so if you don't agree we should consult other folks.

**Comment by vipergtsrz** [comment]
@BartuCulha The default secondary button in the app looks like that on hover. You can see all the buttons at https://prime-deals-dev.vercel.app/storybook

![image](https://user-images.githubusercontent.com/2163332/160162677-9ecc4617-f555-4138-9592-9ca61d2b009d.png)

**Comment by BartuCulha** [comment]
you are right we can close this issue
![PrimeDAO-Design-System-–-Figma (3)](https://user-images.githubusercontent.com/24368665/160814092-e9e078f7-f878-45a2-801c-b5238a1b8997.png)
