### ISSUE TITLE
Secondary Button type should have the same height as other buttons

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#559]
Secondary Button type should have the same height as other buttons
Current:
![DEAL-Dashboard-Prime-Deals (4).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/cb91a708-7195-486b-b1e1-f5e85ef30779)
![Create-a-Partnered-Deal-Prime-Deals (4).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/0a08633d-b3a2-4367-8d67-61ca59226ae3)

Expected:
Secondary button to have the height of 47px

**Comment by curvelabs-dev** [comment]
This is essentially a dup of https://github.com/PrimeDAO/prime-deals-dapp/issues/504
