### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#560]
Connect and Disconnect wallet multiple times until the bug occurs while in Home Page and All deals Page. 
 
**Once the dapp is able to fetch data from Firebase, all issues below resolves automatically

When I have checked to console log I saw this error:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
POST https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Fprime-deals-staging%2Fdatabases%2F(default)&VER=8&gsessionid=CI5StYqiicVVyg1ldG7leQ5cXLAIO_HHzlIwO_G5vyY&SID=ioOPr6EVlbPGbK2wdjKzpg&RID=87793&TYPE=terminate&zx=2vy3738863e3 net::ERR_BLOCKED_BY_CLIENT
xn @ vendors-bb3d84b5.e0e900922b3934908734.bundle.js:2
ei.close @ vendors-bb3d84b5.e0e900922b3934908734.bundle.js:2
Rr @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
close @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
close @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
lo @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
(anonymous) @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
(anonymous) @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
(anonymous) @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
(anonymous) @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
Promise.then (async)
Iu @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
enqueue @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
enqueueAndForget @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
handleDelayElapsed @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2
(anonymous) @ vendors-4e0e0553.6da6942154c25ac65dff.bundle.js:2

All deals Page shows "My Deals" View even when the wallet is disconnected:
![Deals-Prime-Deals (8)](https://user-images.githubusercontent.com/24368665/161713479-a842a362-e5e3-436e-aff8-c1fd2b357aee.png)

Partnered Deals Tab gone from the homepage:
![Uploading Home-Prime-Deals (19).png…]()

**Comment by curvelabs-dev** [comment]
@BartuCulha Can you please provide a clear sense of how to reproduce?

**Comment by BartuCulha** [comment]
Comment updated

**Comment by curvelabs-dev** [comment]
This is probably a dup of: https://github.com/PrimeDAO/prime-deals-dapp/issues/523
