### ISSUE TITLE
Cannot comment to an open proposal

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#563]
Navigate here: https://prime-deals-staging.vercel.app/deal/r8cytTx586WbNKdd194DHe

Connect any wallet

Currently:
Cannot comment under a clause
![DEAL-Dashboard-Prime-Deals (7)](https://user-images.githubusercontent.com/24368665/161738347-0a5449e5-e18b-4988-be8d-ce32fd30ce43.png)

Expected:
To be able to comment

**Comment by giladt** [comment]
@BartuCulha Dup of #479.
