### ISSUE TITLE
Reg. Wizard: Vesting Set up generates a lot of decimals after 2nd decimal

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#594]
1.Navigate here: https://prime-deals-staging.vercel.app/initiate/token-swap/partnered-deal/token-details
2.Enter this to token address: 0xF70d807A0828d2498fa01246c88bA5BaCd70889b
3.Navigate to vesting set up: Enter 1.223 or any number that has 3 decimals

currently:
Instead of displaying1.223, UI will display 1.2229976851851851 
![Edit-an-Open-Proposal-Prime-Deals (2).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/fe7c8581-2055-44a1-930c-0dd8b12ccccf)

Expected:
Display exact written number

**Comment by hiaux0** [comment]
Related #562
