### ISSUE TITLE
Deals not accessible when clicking on "Connect to a Wallet" and choosing Metamask too fast

### ISSUE THREAD

**Issue by hiaux0** [PrimeDAO/prime-deals-dapp#715]
! Just a corner case, not a big deal.
(discovered this while checking out auth-signing PR, and figured to just report this, as this happens on `development`)

Prerequisite:
The app should be loading deals slowly.
(This can be better reproduced locally, because locally, deals load a bit slower from my observations.
Or one has to add a lot of deals, so that loading all deals takes a while.
In that "take a while" moment, one would perfom the steps)

STEPS:
1. Navigate to the Home page
2. Make sure you are not connected. If you are disconnect first.
3. Make sure, deals have not been fully loaded yet (they don't appear in the UI)
1. "Connect to a Wallet", then quickly 
4. Choose Metamask

RESULT:
Issue: Error popup saying "Deals not accessible"
But: after "Decline" or "Accept" deals reload, and display correctly

EXPECTED:
No error popup (it confused me)

https://user-images.githubusercontent.com/30693990/164220958-6034788c-ad20-44e5-835e-fa49f9563dba.mp4

**Comment by renc-curvelabs** [comment]
@hiaux0 I don't understand how to reproduce.  Can you please restructure/rephrase in this form:

STEPS:
1.
2.
...

RESULT:
...
EXPECTED:
...

**Comment by renc-curvelabs** [comment]
Best to wait on working this until the signature feature is done

**Comment by dkent600** [comment]
I just can't seem to click on things fast enough to reproduce this.

**Comment by hiaux0** [comment]
Can't repro anymore

@dkent600 
Could be resolved with the changes you made around deal loading.

Closing.
