### ISSUE TITLE
Deal Clauses should have a text copy below the title

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#760]
Please add this text under the title "Deal Clauses":

` Start a discussion below  by selecting a specific clause.`

### Currently:
![DEAL-Dashboard-Prime-Deals (31).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/1a1bcab6-4453-4956-9f34-9e62ef284510)
### Expected:
![Prime-Deals-–-Figma (38).png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/cd5c5cc3-182d-4fc7-8381-52afb27bf48f)

**Comment by renc-curvelabs** [comment]
We already have this, and it contains other messages depending on the scenario.  The proposal would be a significant UI change that requires approval.  At this time I don't support it.

![image](https://user-images.githubusercontent.com/79934562/165091014-01f85182-9d36-470d-9b3f-0da11d640042.png)

**Comment by BartuCulha** [comment]
Maybe in V2 then
