### ISSUE TITLE
Documentation: Videos should be embedded

### ISSUE THREAD

**Issue by BartuCulha** [PrimeDAO/prime-deals-dapp#962]
1. Navigate here: https://prime-deals-staging.vercel.app/documentation/EditanExistingDeal

### Result: 
Video appears as a link
![Discuss-the-clauses-of-a-Deal-Documentation-Documentation-Prime-Deals.png](https://images.zenhubusercontent.com/609a9f5f0a40bdfde66fe338/6f7aa7c5-43f1-496c-9417-356911c0391b)
### Expected:
If it's a video, it should be embedded just like in the homepage

**Comment by dkent600** [comment]
@ogsamovar I don't think having embedded videos is going to be possible at this time.  There are too many unaddressed issues and hurdles.

What I think you can do is obtain the necessary html for the video player (such as youtube) and embed that html yourself.  Youtube, for example, makes it easy to generate such HTML.

**Comment by ogsamovar** [comment]
I managed to have videos (without youtube) by simply using the `<video>` tag:

`<video controls autoplay width: 100% !important; height: auto !important;> <source src="https://ik.imagekit.io/primedao/PrimeDeals/1-connect-to-a-wallet__vbS8qu1O6.mp4" type="video/mp4"></video>`

<video controls autoplay width: 100% !important; height: auto !important;> <source src="https://ik.imagekit.io/primedao/PrimeDeals/1-connect-to-a-wallet__vbS8qu1O6.mp4" type="video/mp4"></video>
